name: Unit Test(macOS)
on:
  pull_request:
    branches: [master]
jobs:
  ut-mac:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [macos-latest] # macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 25

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install pnpm -g

      - name: Install Dependencies
        run: pnpm install
      
      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test
